apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudevents-go
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/domll/cloudevents-go
        # Uncomment this to send events somewhere.
        #env:
        #- name: K_SINK
        #  value: http://default-broker.default.svc.cluster.local
