apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go-serving
  namespace: default
  annotations:
    networking.knative.dev/disable-auto-tls: "true"
    networking.knative.dev/http-protocol: "redirected"
spec:
  template:
    spec:
      # Target 10 requests in-flight per pod (hard-limit).
      containerConcurrency: 10
      containers:
      - image: docker.io/domll/helloworld-go-serving
        env:
        - name: TARGET
          value: "Go Sample v1"
