apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: grpc-ping
  namespace: default
  annotations:
    networking.knative.dev/disable-auto-tls: "true"
    networking.knative.dev/http-protocol: "redirected"
spec:
  template:
    spec:
      containers:
      - image: docker.io/domll/grpc-ping-go
        ports:
          - name: h2c
            containerPort: 8080

